### ISSUE TITLE
Add heart logo as favicon

### ISSUE THREAD

**Issue by barrymoore** [CDDRC/cddrc_website#4]

**Comment by anderspitman** [comment]
@barrymoore @chmille4 do we have a high quality PNG of the logo somewhere?

**Comment by chmille4** [comment]
@anderspitman here you go
![logo](https://user-images.githubusercontent.com/88370/167682377-a8eb8aac-edb2-45a5-bc4e-3dfd801ad46b.png)

**Comment by anderspitman** [comment]
Done
